<tr>
    <td>
        @component('display.typeimage')
            @slot('type')
                {{$type}}
            @endslot
        @endcomponent
    </td>
    <td>
        {{$name}}
    </td>
    <td>
        {{$quantity}}
    </td>
    <td>
        {{$price}}
    </td>
    <td>
        <a href="/store/package/{{$package}}"><i class="fa fa-folder-open-o"></i></a>
    </td>
</tr>